### ISSUE TITLE
goroutine leak in MySQL sink

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#1160]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

  - pause a changefeed

2. What did you expect to see?

   changefeed stops and all related routines exits

3. What did you see instead?

Some goroutines are leaked

```
goroutine 486812 [semacquire, 1208 minutes]:
sync.runtime_Semacquire(0xc076166f10)
	runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc076166f08)
	sync/waitgroup.go:130 +0x64
github.com/pingcap/ticdc/cdc/sink.(*mysqlSinkWorker).waitAllTxnsExecuted(...)
	github.com/pingcap/ticdc@/cdc/sink/mysql.go:683
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).notifyAndWaitExec.func1(0xc21112d040, 0xc0c7346660)
	github.com/pingcap/ticdc@/cdc/sink/mysql.go:608 +0x51
created by github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).notifyAndWaitExec
	github.com/pingcap/ticdc@/cdc/sink/mysql.go:606 +0x91
```

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.8
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.8
        ```

**Comment by amyangfei** [comment]
have been fixed by #1524, #1929
