### ISSUE TITLE
mysql sink is blocked by mysql client

### ISSUE THREAD

**Issue by leoppro** [pingcap/ticdc#1275]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

stacktrace
```
goroutine 796827 [select, 8715 minutes]:
database/sql.(*DB).conn(0xc00a7a0b40, 0x2d42880, 0xc00d140380, 0x1, 0x0, 0x0, 0x2468940)
	database/sql/sql.go:1183 +0x7ac
database/sql.(*DB).begin(0xc00a7a0b40, 0x2d42880, 0xc00d140380, 0x0, 0x277b101, 0x5, 0x1a, 0x0)
	database/sql/sql.go:1694 +0x4f
database/sql.(*DB).BeginTx(0xc00a7a0b40, 0x2d42880, 0xc00d140380, 0x0, 0xc0214b1aa0, 0xc000591680, 0x14)
	database/sql/sql.go:1676 +0x89
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLWithMaxRetries.func2.3(0xbff3275b5a6b0ef5, 0x71c31e4ffaccb, 0x47bbbe0)
	github.com/pingcap/ticdc@/cdc/sink/mysql.go:793 +0x82
github.com/pingcap/ticdc/cdc/sink.(*Statistics).RecordBatchExecution(0xc00f0c4000, 0xc01615d520, 0x2ce3be0, 0xc0214b1aa0)
	github.com/pingcap/ticdc@/cdc/sink/statistics.go:91 +0x50
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLWithMaxRetries.func2(0xc01615d7d0, 0xc01615d720)
	github.com/pingcap/ticdc@/cdc/sink/mysql.go:792 +0xa7
github.com/pingcap/ticdc/pkg/retry.Run.func1(0xc01615d7a8, 0xc01615d778)
	github.com/pingcap/ticdc@/pkg/retry/retry.go:31 +0x2a
github.com/cenkalti/backoff.RetryNotify(0xc01615d840, 0x2d09ec0, 0xc020d24be0, 0x0, 0x0, 0x0)
	github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:37 +0xb8
github.com/cenkalti/backoff.Retry(...)
	github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:24
github.com/pingcap/ticdc/pkg/retry.Run(0x1dcd6500, 0x8, 0xc01615d8c8, 0x60, 0x25f0220)
	github.com/pingcap/ticdc@/pkg/retry/retry.go:30 +0xb8
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLWithMaxRetries(0xc000e7f040, 0x2d42880, 0xc00d140380, 0xc020d265f0, 0x8, 0x0, 0x17, 0x0)
	github.com/pingcap/ticdc@/cdc/sink/mysql.go:784 +0xf1
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLs(0xc000e7f040, 0x2d42880, 0xc00d140380, 0xc029f095a8, 0x1, 0x1, 0x0, 0x0, 0x1, 0x1)
	github.com/pingcap/ticdc@/cdc/sink/mysql.go:937 +0x3dd
github.com/pingcap/ticdc/cdc/sink.(*mysqlSinkWorker).run.func2(0xc0131256e0, 0xc013125614)
	github.com/pingcap/ticdc@/cdc/sink/mysql.go:723 +0x149
github.com/pingcap/ticdc/cdc/sink.(*mysqlSinkWorker).run(0xc003f809b0, 0x2d42880, 0xc00d140380, 0x0, 0x0)
	github.com/pingcap/ticdc@/cdc/sink/mysql.go:755 +0x4e0
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).createSinkWorkers.func1(0xc003f809b0, 0x2d42880, 0xc00d140380, 0xc000e7f040)
	github.com/pingcap/ticdc@/cdc/sink/mysql.go:592 +0x43
created by github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).createSinkWorkers
	github.com/pingcap/ticdc@/cdc/sink/mysql.go:591 +0xbc
```

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.8
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.8
        ```

**Comment by leoppro** [comment]
asktug link:https://asktug.com/t/topic/67450/12

**Comment by amyangfei** [comment]
Go Version: go version go1.13 linux/amd64

**Comment by glkappe** [comment]
follow
