### ISSUE TITLE
panic found in kvclient

### ISSUE THREAD

**Issue by leoppro** [pingcap/ticdc#1457]
## Bug Report

```
panic: unlocking a not locked range

goroutine 3727 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc07bf4ae40, 0xc020d66a00, 0x5, 0x5)
	/go/pkg/mod/go.uber.org/zap@v1.16.0/zapcore/entry.go:234 +0x735
go.uber.org/zap.(*Logger).Panic(0xc081ea4180, 0x53ee17c, 0x1c, 0xc020d66a00, 0x5, 0x5)
	/go/pkg/mod/go.uber.org/zap@v1.16.0/logger.go:226 +0x96
github.com/pingcap/log.Panic(0x53ee17c, 0x1c, 0xc020d66a00, 0x5, 0x5)
	/go/pkg/mod/github.com/pingcap/log@v0.0.0-20201112100606-8f1e84a3abc8/global.go:50 +0xf1
github.com/pingcap/ticdc/pkg/regionspan.(*RegionRangeLock).UnlockRange(0xc041c8dcb0, 0xc041eac960, 0x12, 0x12, 0xc041eac980, 0x12, 0x12, 0xb8, 0x22, 0x5df75bab0980001)
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/pkg/regionspan/region_range_lock.go:321 +0x28d7
github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).onRegionFail(0xc03b4377a0, 0x5ef5ae0, 0xc03c154b00, 0xb8, 0x19, 0x22, 0xc041eac960, 0x12, 0x12, 0xc041eac980, ...)
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:650 +0x504
github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).dispatchRequest(0xc03b4377a0, 0x5ef5ae0, 0xc03c154b00, 0xc041c8df80, 0xc000000001, 0x54b)
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:707 +0x34b3
github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).eventFeed.func1(0xc010eacf68, 0x1)
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:558 +0xa1
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc041c8df80, 0xc041c8dfb0)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x72
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x74

```
In PR: https://github.com/pingcap/ticdc/pull/1187
CI link: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/4557/pipeline/85

logs:
[processor_panic.zip](https://github.com/pingcap/ticdc/files/6048470/processor_panic.zip)

**Comment by amyangfei** [comment]
It is an old bug, v4.0.10 also has similar panic

```
panic: unlocking a not locked range

goroutine 846 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0ccc00300, 0xc1198d9a40, 0x5, 0x5)
        go.uber.org/zap@v1.16.0/zapcore/entry.go:234 +0x585
go.uber.org/zap.(*Logger).Panic(0xc11a19ac60, 0x284acf6, 0x1c, 0xc1198d9a40, 0x5, 0x5)
        go.uber.org/zap@v1.16.0/logger.go:226 +0x85
github.com/pingcap/log.Panic(0x284acf6, 0x1c, 0xc1198d9a40, 0x5, 0x5)
        github.com/pingcap/log@v0.0.0-20201112100606-8f1e84a3abc8/global.go:50 +0x10b
github.com/pingcap/ticdc/pkg/regionspan.(*RegionRangeLock).UnlockRange(0xc002f85890, 0xc1021e5820, 0x1b, 0x20, 0xc1021e5840, 0x1b, 0x20, 0x2f65a4e, 0xc697, 0x5de3246ab1c000a)
        github.com/pingcap/ticdc/pkg/regionspan/region_range_lock.go:321 +0x2145
github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).onRegionFail(0xc00097e400, 0x2c2d0a0, 0xc002fa45c0, 0x2f65a4e, 0x320, 0xc697, 0xc1021e5820, 0x1b, 0x20, 0xc1021e5840, ...)
        github.com/pingcap/ticdc/cdc/kv/client.go:613 +0x335
github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).dispatchRequest(0xc00097e400, 0x2c2d0a0, 0xc002fa45c0, 0xc002f85b00, 0x12, 0x12)
        github.com/pingcap/ticdc/cdc/kv/client.go:670 +0x245a
github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).eventFeed.func1(0x2c2d0a0, 0xc00273dd80)
        github.com/pingcap/ticdc/cdc/kv/client.go:521 +0x45
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc002f85b00, 0xc002f85b30)
        golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x66
panic: tikv reported duplicated request to the same region, which is not expected

goroutine 4736042 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0a38aa780, 0xc0aba8ef80, 0x1, 0x1)
        go.uber.org/zap@v1.16.0/zapcore/entry.go:234 +0x585
go.uber.org/zap.(*Logger).Panic(0xc0b52ff680, 0x28c24fe, 0x4a, 0xc0aba8ef80, 0x1, 0x1)
        go.uber.org/zap@v1.16.0/logger.go:226 +0x85
github.com/pingcap/log.Panic(0x28c24fe, 0x4a, 0xc0aba8ef80, 0x1, 0x1)
        github.com/pingcap/log@v0.0.0-20201112100606-8f1e84a3abc8/global.go:50 +0x10b
github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).handleError(0xc0211ee000, 0x2c2d0a0, 0xc029604300, 0x41bee27, 0x1b2, 0x975e, 0xc0a2c06920, 0x1b, 0x20, 0xc0a2c06960, ...)
        github.com/pingcap/ticdc/cdc/kv/client.go:1004 +0x90c
github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).eventFeed.func3(0x10, 0x0)
        github.com/pingcap/ticdc/cdc/kv/client.go:546 +0x1e5
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc036d92030, 0xc0359b8d80)
        golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x66
```

Need investigation
