### ISSUE TITLE
Another resolved ts not forward issue caused by slow error handling

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#1612]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   - Setup a tidb cluster with 300K regions (100K leader)
   - Start ticdc changefeed from start-ts one day ago

2. What did you expect to see?

    the replication is normal

3. What did you see instead?

    - The resolved ts doesn't forward
    - Goroutine observation
      - In goroutines dump, we found the `onRegionFail` call is accumulated more and more, which means the region reconnect throughput is larger than ticdc handling throughput
      - Different from #1599, since no `LockRange` blocking or other goroutine blocking is found

goroutines log: 
[goroutines.tar.gz](https://github.com/pingcap/ticdc/files/6263649/goroutines.tar.gz)

sample:
```
goroutine 464041 [select, 16 minutes]:
github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).onRegionFail.func1(0xc002c7a000, 0xc022f01f80, 0x2ff4d40, 0xc002a96000)
        github.com/pingcap/ticdc/cdc/kv/client.go:675 +0x107
created by github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).onRegionFail
        github.com/pingcap/ticdc/cdc/kv/client.go:674 +0x434
```

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        5.0.0

    - TiCDC version (execute `cdc version`):

        5.0.0@https://github.com/pingcap/ticdc/commit/39c1bd9ba9c3ab0e704d03a58df0360501e9f3bd

**Comment by amyangfei** [comment]
Another problem, found resolved lock costs too mush CPU

cpu profile file: 
[cpu.profile.tar.gz](https://github.com/pingcap/ticdc/files/6263882/cpu.profile.tar.gz)


![image](https://user-images.githubusercontent.com/1527315/113695937-02594400-9704-11eb-883c-ccf9e40a4a45.png)
