### ISSUE TITLE
unstable unit test frontier.(*tsHeapSuite).TestUpdateTs timeout

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#2345]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```
[2021-07-21T06:34:17.903Z] coverage: 90.3% of statements
[2021-07-21T06:34:17.903Z] panic: test timed out after 10m0s
[2021-07-21T06:34:17.903Z] 
[2021-07-21T06:34:17.903Z] goroutine 75 [running]:
[2021-07-21T06:34:17.903Z] testing.(*M).startAlarm.func1()
[2021-07-21T06:34:17.903Z] 	/usr/local/go/src/testing/testing.go:1700 +0x11f
[2021-07-21T06:34:17.903Z] created by time.goFunc
[2021-07-21T06:34:17.903Z] 	/usr/local/go/src/time/sleep.go:180 +0x52
[2021-07-21T06:34:17.903Z] 
[2021-07-21T06:34:17.903Z] goroutine 1 [chan receive, 9 minutes]:
[2021-07-21T06:34:17.903Z] testing.(*T).Run(0xc000001800, 0x15d9eec, 0x4, 0x1641db8, 0x0)
[2021-07-21T06:34:17.903Z] 	/usr/local/go/src/testing/testing.go:1239 +0x610
[2021-07-21T06:34:17.903Z] testing.runTests.func1(0xc000001800)
[2021-07-21T06:34:17.903Z] 	/usr/local/go/src/testing/testing.go:1511 +0xa7
[2021-07-21T06:34:17.903Z] testing.tRunner(0xc000001800, 0xc000261c78)
[2021-07-21T06:34:17.903Z] 	/usr/local/go/src/testing/testing.go:1193 +0x203
[2021-07-21T06:34:17.903Z] testing.runTests(0xc00049c168, 0x20cbe10, 0x1, 0x1, 0xc0360dd96ae89658, 0x8bb43594ef, 0x21026c0, 0xc0001ac148)
[2021-07-21T06:34:17.903Z] 	/usr/local/go/src/testing/testing.go:1509 +0x613
[2021-07-21T06:34:17.903Z] testing.(*M).Run(0xc000499100, 0x0)
[2021-07-21T06:34:17.903Z] 	/usr/local/go/src/testing/testing.go:1417 +0x3b4
[2021-07-21T06:34:17.903Z] main.main()
[2021-07-21T06:34:17.903Z] 	_testmain.go:99 +0x357
[2021-07-21T06:34:17.903Z] 
[2021-07-21T06:34:17.903Z] goroutine 7 [select, 4 minutes]:
[2021-07-21T06:34:17.903Z] github.com/pingcap/check.(*suiteRunner).doRun(0xc0003b4cf0, 0x0)
[2021-07-21T06:34:17.903Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:667 +0x225
[2021-07-21T06:34:17.903Z] github.com/pingcap/check.(*suiteRunner).run(0xc0003b4cf0, 0x2131c68)
[2021-07-21T06:34:17.903Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:696 +0x145
[2021-07-21T06:34:17.903Z] github.com/pingcap/check.Run(0x14d0680, 0x2131c68, 0xc0001b1e50, 0xc0003b4ea0)
[2021-07-21T06:34:17.903Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:150 +0x5b
[2021-07-21T06:34:17.903Z] github.com/pingcap/check.RunAll(0xc0001b1e50, 0x0)
[2021-07-21T06:34:17.903Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:113 +0xff7
[2021-07-21T06:34:17.903Z] github.com/pingcap/check.TestingT(0xc000001980)
[2021-07-21T06:34:17.903Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:99 +0x757
[2021-07-21T06:34:17.903Z] github.com/pingcap/ticdc/cdc/puller/frontier.Test(0xc000001980)
[2021-07-21T06:34:17.903Z] 	/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/cdc/puller/frontier/frontier_test.go:29 +0x39
[2021-07-21T06:34:17.903Z] testing.tRunner(0xc000001980, 0x1641db8)
[2021-07-21T06:34:17.903Z] 	/usr/local/go/src/testing/testing.go:1193 +0x203
[2021-07-21T06:34:17.903Z] created by testing.(*T).Run
[2021-07-21T06:34:17.903Z] 	/usr/local/go/src/testing/testing.go:1238 +0x5d8
[2021-07-21T06:34:17.903Z] 
[2021-07-21T06:34:17.903Z] goroutine 73 [select, 4 minutes]:
[2021-07-21T06:34:17.904Z] github.com/pingcap/check.(*resultTracker)._loopRoutine(0xc0003b4c60)
[2021-07-21T06:34:17.904Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:464 +0x185
[2021-07-21T06:34:17.904Z] created by github.com/pingcap/check.(*resultTracker).start
[2021-07-21T06:34:17.904Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:444 +0x4d
[2021-07-21T06:34:17.904Z] 
[2021-07-21T06:34:17.904Z] goroutine 32 [runnable]:
[2021-07-21T06:34:17.904Z] github.com/pingcap/ticdc/cdc/puller/frontier.(*tsHeapSuite).TestUpdateTs(0x2131c68, 0xc000496000)
[2021-07-21T06:34:17.904Z] 	/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/cdc/puller/frontier/heap_test.go:52 +0x23e
[2021-07-21T06:34:17.904Z] reflect.Value.call(0x14d0680, 0x2131c68, 0xa13, 0x15d9bf4, 0x4, 0xc0000c8ef0, 0x1, 0x1, 0xc00030b508, 0x13c3afe, ...)
[2021-07-21T06:34:17.904Z] 	/usr/local/go/src/reflect/value.go:476 +0x99c
[2021-07-21T06:34:17.904Z] reflect.Value.Call(0x14d0680, 0x2131c68, 0xa13, 0xc00030b6f0, 0x1, 0x1, 0x0, 0x0, 0x0)
[2021-07-21T06:34:17.904Z] 	/usr/local/go/src/reflect/value.go:337 +0xd9
[2021-07-21T06:34:17.904Z] github.com/pingcap/check.(*suiteRunner).forkTest.func1(0xc000496000)
[2021-07-21T06:34:17.904Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xb3c
[2021-07-21T06:34:17.904Z] github.com/pingcap/check.(*suiteRunner).forkCall.func1(0xc0003b4cf0, 0xc000496000, 0xc000129cc0)
[2021-07-21T06:34:17.904Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x11e
[2021-07-21T06:34:17.904Z] created by github.com/pingcap/check.(*suiteRunner).forkCall
[2021-07-21T06:34:17.904Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4cd
[2021-07-21T06:34:17.904Z] FAIL	github.com/pingcap/ticdc/cdc/puller/frontier	600.162s
```

2. Versions of the cluster

    - TiCDC version (execute `cdc version`):

        master@https://github.com/pingcap/ticdc/commit/675aea7ad8045298ac88dad5913845c363c53326

**Comment by ben1009** [comment]
run 100 times at local, can not reproduce
=== RUN   Test
OK: 1 passed
--- PASS: Test (340.92s)
![image](https://user-images.githubusercontent.com/1741864/129322995-89103674-2c3b-4e79-b546-3ba690e6ab82.png)

**Comment by amyangfei** [comment]
From the stack, the test is running

```
[2021-07-21T06:34:17.904Z] goroutine 32 [runnable]:
[2021-07-21T06:34:17.904Z] github.com/pingcap/ticdc/cdc/puller/frontier.(*tsHeapSuite).TestUpdateTs(0x2131c68, 0xc000496000)
[2021-07-21T06:34:17.904Z] 	/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/cdc/puller/frontier/heap_test.go:52 +0x23e
```

and the test is terminated by timeout (default 10minutes)

```
```
