### ISSUE TITLE
unstable unit test frontier.(*tsHeapSuite).TestRemoveNode timeout

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#2614]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```
[2021-08-24T05:19:57.949Z] panic: test timed out after 10m0s
[2021-08-24T05:19:57.949Z] 
[2021-08-24T05:19:57.949Z] goroutine 68 [running]:
[2021-08-24T05:19:57.949Z] testing.(*M).startAlarm.func1()
[2021-08-24T05:19:57.949Z] 	/usr/local/go/src/testing/testing.go:1700 +0x11f
[2021-08-24T05:19:57.949Z] created by time.goFunc
[2021-08-24T05:19:57.949Z] 	/usr/local/go/src/time/sleep.go:180 +0x52
[2021-08-24T05:19:57.949Z] 
[2021-08-24T05:19:57.949Z] goroutine 1 [chan receive, 9 minutes]:
[2021-08-24T05:19:57.949Z] testing.(*T).Run(0xc000001b00, 0x15da0ec, 0x4, 0x1642120, 0x0)
[2021-08-24T05:19:57.949Z] 	/usr/local/go/src/testing/testing.go:1239 +0x610
[2021-08-24T05:19:57.949Z] testing.runTests.func1(0xc000001b00)
[2021-08-24T05:19:57.949Z] 	/usr/local/go/src/testing/testing.go:1511 +0xa7
[2021-08-24T05:19:57.949Z] testing.tRunner(0xc000001b00, 0xc000261c78)
[2021-08-24T05:19:57.949Z] 	/usr/local/go/src/testing/testing.go:1193 +0x203
[2021-08-24T05:19:57.950Z] testing.runTests(0xc000422870, 0x20cde10, 0x1, 0x1, 0xc0413e3c018c0434, 0x8bb6066440, 0x21046e0, 0xc00012a148)
[2021-08-24T05:19:57.950Z] 	/usr/local/go/src/testing/testing.go:1509 +0x613
[2021-08-24T05:19:57.950Z] testing.(*M).Run(0xc000489000, 0x0)
[2021-08-24T05:19:57.950Z] 	/usr/local/go/src/testing/testing.go:1417 +0x3b4
[2021-08-24T05:19:57.950Z] main.main()
[2021-08-24T05:19:57.950Z] 	_testmain.go:99 +0x357
[2021-08-24T05:19:57.950Z] 
[2021-08-24T05:19:57.950Z] goroutine 9 [select, 7 minutes]:
[2021-08-24T05:19:57.950Z] github.com/pingcap/check.(*suiteRunner).doRun(0xc0000f5cb0, 0x0)
[2021-08-24T05:19:57.950Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:667 +0x225
[2021-08-24T05:19:57.950Z] github.com/pingcap/check.(*suiteRunner).run(0xc0000f5cb0, 0x2133c68)
[2021-08-24T05:19:57.950Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:696 +0x145
[2021-08-24T05:19:57.950Z] github.com/pingcap/check.Run(0x14d07e0, 0x2133c68, 0xc00012fe50, 0xc0003fc1b0)
[2021-08-24T05:19:57.950Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:150 +0x5b
[2021-08-24T05:19:57.950Z] github.com/pingcap/check.RunAll(0xc00012fe50, 0x0)
[2021-08-24T05:19:57.950Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:113 +0xff7
[2021-08-24T05:19:57.950Z] github.com/pingcap/check.TestingT(0xc000001c80)
[2021-08-24T05:19:57.950Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:99 +0x757
[2021-08-24T05:19:57.950Z] github.com/pingcap/ticdc/cdc/puller/frontier.Test(0xc000001c80)
[2021-08-24T05:19:57.950Z] 	/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/cdc/puller/frontier/frontier_test.go:29 +0x39
[2021-08-24T05:19:57.950Z] testing.tRunner(0xc000001c80, 0x1642120)
[2021-08-24T05:19:57.950Z] 	/usr/local/go/src/testing/testing.go:1193 +0x203
[2021-08-24T05:19:57.950Z] created by testing.(*T).Run
[2021-08-24T05:19:57.950Z] 	/usr/local/go/src/testing/testing.go:1238 +0x5d8
[2021-08-24T05:19:57.950Z] 
[2021-08-24T05:19:57.950Z] goroutine 98 [select, 7 minutes]:
[2021-08-24T05:19:57.950Z] github.com/pingcap/check.(*resultTracker)._loopRoutine(0xc0000f5c20)
[2021-08-24T05:19:57.950Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:464 +0x185
[2021-08-24T05:19:57.950Z] created by github.com/pingcap/check.(*resultTracker).start
[2021-08-24T05:19:57.950Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:444 +0x4d
[2021-08-24T05:19:57.950Z] 
[2021-08-24T05:19:57.950Z] goroutine 100 [runnable]:
[2021-08-24T05:19:57.950Z] github.com/pingcap/ticdc/cdc/puller/frontier.(*tsHeapSuite).TestRemoveNode(0x2133c68, 0xc0004820f0)
[2021-08-24T05:19:57.950Z] 	/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/cdc/puller/frontier/heap_test.go:87 +0x272
[2021-08-24T05:19:57.950Z] reflect.Value.call(0x14d07e0, 0x2133c68, 0x613, 0x15d9df4, 0x4, 0xc0000c6ef0, 0x1, 0x1, 0xc0004a5d08, 0x13c3d9e, ...)
[2021-08-24T05:19:57.950Z] 	/usr/local/go/src/reflect/value.go:476 +0x99c
[2021-08-24T05:19:57.950Z] reflect.Value.Call(0x14d07e0, 0x2133c68, 0x613, 0xc0004a5ef0, 0x1, 0x1, 0x0, 0x0, 0x0)
[2021-08-24T05:19:57.950Z] 	/usr/local/go/src/reflect/value.go:337 +0xd9
[2021-08-24T05:19:57.950Z] github.com/pingcap/check.(*suiteRunner).forkTest.func1(0xc0004820f0)
[2021-08-24T05:19:57.950Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xb3c
[2021-08-24T05:19:57.950Z] github.com/pingcap/check.(*suiteRunner).forkCall.func1(0xc0000f5cb0, 0xc0004820f0, 0xc0000de940)
[2021-08-24T05:19:57.950Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x11e
[2021-08-24T05:19:57.950Z] created by github.com/pingcap/check.(*suiteRunner).forkCall
[2021-08-24T05:19:57.950Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4cd
```

2. Versions of the cluster

    - TiCDC version (execute `cdc version`):

        master@https://github.com/pingcap/ticdc/commit/d0bb869a3b9995d01e4d104864782f9125f192de

**Comment by amyangfei** [comment]
This failure is quite similar to #2345, would you please take a look @ben1009
