### ISSUE TITLE
unit test etcdWorkerSuite.TestEtcdSum panic

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#2731]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```
[2021-09-02T05:59:10.125Z] {"level":"warn","ts":"2021-09-02T13:57:41.195+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-3d261a18-5c76-45f3-abfe-2bf0a8220b4e/127.0.0.1:41209","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2021-09-02T05:59:10.125Z] {"level":"warn","ts":"2021-09-02T13:57:41.195+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-3d261a18-5c76-45f3-abfe-2bf0a8220b4e/127.0.0.1:41209","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2021-09-02T05:59:10.125Z] {"level":"warn","ts":"2021-09-02T13:57:41.195+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-3d261a18-5c76-45f3-abfe-2bf0a8220b4e/127.0.0.1:41209","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2021-09-02T05:59:10.125Z] {"level":"warn","ts":"2021-09-02T13:57:41.195+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-3d261a18-5c76-45f3-abfe-2bf0a8220b4e/127.0.0.1:41209","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2021-09-02T05:59:10.125Z] {"level":"warn","ts":"2021-09-02T13:57:41.195+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-3d261a18-5c76-45f3-abfe-2bf0a8220b4e/127.0.0.1:41209","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2021-09-02T05:59:10.125Z] {"level":"warn","ts":"2021-09-02T13:57:41.195+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-3d261a18-5c76-45f3-abfe-2bf0a8220b4e/127.0.0.1:41209","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2021-09-02T05:59:10.125Z] {"level":"warn","ts":"2021-09-02T13:57:41.197+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-3d261a18-5c76-45f3-abfe-2bf0a8220b4e/127.0.0.1:41209","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2021-09-02T05:59:10.125Z] {"level":"warn","ts":"2021-09-02T13:57:41.195+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-3d261a18-5c76-45f3-abfe-2bf0a8220b4e/127.0.0.1:41209","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2021-09-02T05:59:10.125Z] {"level":"warn","ts":"2021-09-02T13:57:41.195+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-3d261a18-5c76-45f3-abfe-2bf0a8220b4e/127.0.0.1:41209","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2021-09-02T05:59:10.125Z] {"level":"warn","ts":"2021-09-02T13:58:45.648+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-09a14372-9aa2-44b4-b9d7-b48fad1955d9/127.0.0.1:44322","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
[2021-09-02T05:59:10.126Z] {"level":"warn","ts":"2021-09-02T13:58:45.650+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-6e3e12f3-7230-48c6-ba0a-5dbf0449eaed/127.0.0.1:44322","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
[2021-09-02T05:59:10.126Z] {"level":"warn","ts":"2021-09-02T13:58:45.650+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-0c3fcbfa-6dd4-4d58-913c-403f306b5b97/127.0.0.1:44322","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
[2021-09-02T05:59:10.126Z] {"level":"warn","ts":"2021-09-02T13:58:45.650+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-b2d41b11-ec4d-497a-8caf-78f2190681cd/127.0.0.1:44322","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
[2021-09-02T05:59:10.126Z] 
[2021-09-02T05:59:10.126Z] ----------------------------------------------------------------------
[2021-09-02T05:59:10.126Z] FAIL: etcd_worker_test.go:215: etcdWorkerSuite.TestEtcdSum
[2021-09-02T05:59:10.126Z] 
[2021-09-02T05:59:10.126Z] etcd_worker_test.go:279:
[2021-09-02T05:59:10.126Z]     c.Check(err, check.IsNil)
[2021-09-02T05:59:10.126Z] ... value *errors.withStack = etcdserver: request timed out ("etcdserver: request timed out")
[2021-09-02T05:59:10.126Z] 
[2021-09-02T05:59:10.126Z] {"level":"warn","ts":"2021-09-02T13:59:00.105+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-7a5df364-0ca2-4a9f-90ed-8630b0ad6705/127.0.0.1:39958","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
[2021-09-02T05:59:10.126Z] [2021/09/02 13:59:05.584 +08:00] [PANIC] [etcd_worker_test.go:310] ["linearizability check failed"] [expected=1011] [actual=1010] [stack="github.com/pingcap/ticdc/pkg/orchestrator.(*linearizabilityReactor).Tick\n\t/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/pkg/orchestrator/etcd_worker_test.go:310\ngithub.com/pingcap/ticdc/pkg/orchestrator.(*EtcdWorker).Run\n\t/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/pkg/orchestrator/etcd_worker.go:187\ngithub.com/pingcap/ticdc/pkg/orchestrator.(*etcdWorkerSuite).TestLinearizability.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/pkg/orchestrator/etcd_worker_test.go:347\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57"]
[2021-09-02T05:59:10.126Z] panic: linearizability check failed
[2021-09-02T05:59:10.126Z] 
[2021-09-02T05:59:10.126Z] goroutine 29817 [running]:
[2021-09-02T05:59:10.126Z] go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0001ce0c0, 0xc0006f0800, 0x2, 0x2)
[2021-09-02T05:59:10.126Z] 	/nfs/cache/mod/go.uber.org/zap@v1.16.0/zapcore/entry.go:234 +0x76d
[2021-09-02T05:59:10.126Z] go.uber.org/zap.(*Logger).Panic(0xc000c7ea20, 0x161254e, 0x1c, 0xc0006f0800, 0x2, 0x2)
[2021-09-02T05:59:10.126Z] 	/nfs/cache/mod/go.uber.org/zap@v1.16.0/logger.go:226 +0x9b
[2021-09-02T05:59:10.126Z] github.com/pingcap/log.Panic(0x161254e, 0x1c, 0xc0006f0800, 0x2, 0x2)
[2021-09-02T05:59:10.126Z] 	/nfs/cache/mod/github.com/pingcap/log@v0.0.0-20210317133921-96f4fcab92a4/global.go:53 +0xf1
[2021-09-02T05:59:10.126Z] github.com/pingcap/ticdc/pkg/orchestrator.(*linearizabilityReactor).Tick(0xc000686e40, 0x17f2b40, 0xc000564120, 0x17e4208, 0xc00012e580, 0x1, 0x0, 0x1, 0x0)
[2021-09-02T05:59:10.126Z] 	/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/pkg/orchestrator/etcd_worker_test.go:310 +0x52a
[2021-09-02T05:59:10.126Z] github.com/pingcap/ticdc/pkg/orchestrator.(*EtcdWorker).Run(0xc0002ccfc0, 0x17f2b40, 0xc000564120, 0x0, 0x989680, 0x0, 0x0)
[2021-09-02T05:59:10.126Z] 	/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/pkg/orchestrator/etcd_worker.go:187 +0xafd
[2021-09-02T05:59:10.126Z] github.com/pingcap/ticdc/pkg/orchestrator.(*etcdWorkerSuite).TestLinearizability.func1(0xc000eeb750, 0xc000566700)
[2021-09-02T05:59:10.126Z] 	/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/pkg/orchestrator/etcd_worker_test.go:347 +0x6a
[2021-09-02T05:59:10.126Z] golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0006b2360, 0xc00037d780)
[2021-09-02T05:59:10.126Z] 	/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x95
[2021-09-02T05:59:10.126Z] created by golang.org/x/sync/errgroup.(*Group).Go
[2021-09-02T05:59:10.126Z] 	/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x74
```

2. Versions of the cluster

    - TiCDC version (execute `cdc version`):

        master@https://github.com/pingcap/ticdc/commit/c97efbe2c642d9b857e534ac162a8e75de5375f4

**Comment by hi-rustin** [comment]
It doesn't seem to be happening again, close it for now. If you guys still encounter it please give feedback and reopen it.
