### ISSUE TITLE
kv client v1 met panic unexpected fault address

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#2770]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```
unexpected fault address 0x211cb76
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x211cb76 pc=0x211cb76]

goroutine 46172 [running]:
runtime.throw(0x2c179eb, 0x5)
	runtime/panic.go:774 +0x72 fp=0xc0c63acc08 sp=0xc0c63acbd8 pc=0x42f692
runtime.sigpanic()
	runtime/signal_unix.go:401 +0x3de fp=0xc0c63acc38 sp=0xc0c63acc08 pc=0x444d1e
github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).singleEventFeed(0xc00205a000, 0x32b7e80, 0xc0014a4480, 0x15e3de1, 0xc0671ba420, 0xab, 0xb0, 0xc0671ba4d0, 0xab, 0xb0, ...)
	github.com/pingcap/ticdc@/cdc/kv/client.go:1561 +0xdc6 fp=0xc0c63ad9e8 sp=0xc0c63acc38 pc=0x211cb76
github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).partialRegionFeed(0xc00205a000, 0x32b7e80, 0xc0014a4480, 0xc0670b8b00, 0xc0623e88c0, 0x0, 0x0)
	github.com/pingcap/ticdc@/cdc/kv/client.go:903 +0x13c fp=0xc0c63adf10 sp=0xc0c63ad9e8 pc=0x2116a2c
github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).sendRegionChangeEvent.func1(0xc0762b6768, 0x0)
	github.com/pingcap/ticdc@/cdc/kv/client.go:1270 +0x4e fp=0xc0c63adf58 sp=0xc0c63adf10 pc=0x213971e
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0006b9710, 0xc0c62470b0)
	golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x64 fp=0xc0c63adfd0 sp=0xc0c63adf58 pc=0x135f124
runtime.goexit()
	runtime/asm_amd64.s:1357 +0x1 fp=0xc0c63adfd8 sp=0xc0c63adfd0 pc=0x45f6e1
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x66
```

https://github.com/pingcap/ticdc/blob/6363c4810edf2e25f63df28ace9b6f0a2939c6b9/cdc/kv/client.go#L1561

```
if event.resolvedTs != nil {
	if err := handleResolvedTs(event.resolvedTs.Ts); err != nil {  <---- panic in this line
		return lastResolvedTs, errors.Trace(err)
	}
}
```
2. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v5.0.1
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v5.0.1
        ```

**Comment by amyangfei** [comment]
May be related with runtime GC bug, not sure

**Comment by overvenus** [comment]
Client v1 is deprecated in the latest release.
