### ISSUE TITLE
kv client panic

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#317]
test on pr #308 

```
fatal error: sync: RUnlock of unlocked RWMutex

goroutine 508 [running]:
runtime.throw(0x1e130ef, 0x21)
	runtime/panic.go:774 +0x72 fp=0xc0017637f0 sp=0xc0017637c0 pc=0x42f612
sync.throw(0x1e130ef, 0x21)
	runtime/panic.go:760 +0x35 fp=0xc001763810 sp=0xc0017637f0 pc=0x42f595
sync.(*RWMutex).rUnlockSlow(0xc0008b64a0, 0xc0bfffffff)
	sync/rwmutex.go:80 +0x3f fp=0xc001763838 sp=0xc001763810 pc=0x46f42f
sync.(*RWMutex).RUnlock(...)
	sync/rwmutex.go:70
github.com/pingcap/ticdc/cdc/kv.(*CDCClient).receiveFromStream(0xc0006365d0, 0x2128360, 0xc000944000, 0xc0001cef90, 0xc000051fe0, 0x12, 0x5, 0x2145bc0, 0xc0007405a0, 0xc000445860, ...)
	github.com/pingcap/ticdc@/cdc/kv/client.go:563 +0x3a4 fp=0xc001763ec8 sp=0xc001763838 pc=0x14391b4
github.com/pingcap/ticdc/cdc/kv.(*CDCClient).dispatchRequest.func1(0xc0008ad768, 0x0)
	github.com/pingcap/ticdc@/cdc/kv/client.go:290 +0xc2 fp=0xc001763f58 sp=0xc001763ec8 pc=0x1443612
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0001cef90, 0xc00016ad20)
	golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x64 fp=0xc001763fd0 sp=0xc001763f58 pc=0xe0da34
runtime.goexit()
	runtime/asm_amd64.s:1357 +0x1 fp=0xc001763fd8 sp=0xc001763fd0 pc=0x45f131
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
```

full stdout log: http://139.219.11.38:8000/suZMH/20200306_1258_cdc_stdout.log

**Comment by amyangfei** [comment]
http://139.219.11.38:8000/vbE0X/20200306_1311_cdc.log
