### ISSUE TITLE
loader panic: send on closed channel

### ISSUE THREAD

**Issue by glorv** [pingcap/ticdc#3380]
### What did you do?

See: https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/448/pipeline/144/

```
[2021-11-10T09:52:22.905Z] + echo /tmp/dm_test/import_goroutine_leak/worker1/log/stdout.log
[2021-11-10T09:52:22.905Z] /tmp/dm_test/import_goroutine_leak/worker1/log/stdout.log
[2021-11-10T09:52:22.905Z] + cat /tmp/dm_test/import_goroutine_leak/worker1/log/stdout.log
[2021-11-10T09:52:22.905Z] dm-worker startup 2021-11-10 17:50:58.031442467 +0800 CST m=+0.388230346
[2021-11-10T09:52:22.905Z] panic: send on closed channel
[2021-11-10T09:52:22.905Z] 
[2021-11-10T09:52:22.905Z] goroutine 385 [running]:
[2021-11-10T09:52:22.905Z] github.com/pingcap/ticdc/dm/loader.(*Worker).run.func2()
[2021-11-10T09:52:22.905Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/ticdc/dm/loader/loader.go:206 +0xd30
[2021-11-10T09:52:22.905Z] github.com/pingcap/ticdc/dm/loader.(*Worker).run.func3(0xc001164ea0, 0xc00059d740)
[2021-11-10T09:52:22.905Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/ticdc/dm/loader/loader.go:249 +0x8a
[2021-11-10T09:52:22.905Z] created by github.com/pingcap/ticdc/dm/loader.(*Worker).run
[2021-11-10T09:52:22.905Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/ticdc/dm/loader/loader.go:247 +0x4ba
[2021-11-10T09:52:22.905Z] dm-worker startup 2021-11-10 17:51:03.317097776 +0800 CST m=+0.758201490
[2021-11-10T09:52:22.905Z] panic: send on closed channel
[2021-11-10T09:52:22.905Z] 
[2021-11-10T09:52:22.905Z] goroutine 504 [running]:
[2021-11-10T09:52:22.905Z] github.com/pingcap/ticdc/dm/loader.(*Worker).run(0xc000c39200, 0x742e4c8, 0xc000a92a80, 0xc000c389c0, 0xc000c38a80)
[2021-11-10T09:52:22.905Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/ticdc/dm/loader/loader.go:257 +0x850
[2021-11-10T09:52:22.905Z] github.com/pingcap/ticdc/dm/loader.(*Loader).initAndStartWorkerPool.func1(0xc000e669a0, 0xc000c39200, 0x742e4c8, 0xc000a92a80)
[2021-11-10T09:52:22.905Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/ticdc/dm/loader/loader.go:934 +0x134
[2021-11-10T09:52:22.905Z] created by github.com/pingcap/ticdc/dm/loader.(*Loader).initAndStartWorkerPool
[2021-11-10T09:52:22.905Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/ticdc/dm/loader/loader.go:932 +0xfb
```

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lance6716** [comment]
remember this is expected 😂 

https://github.com/pingcap/ticdc/blob/2569abaa3e64bc930b5cab18a0d6edaae2a41ef0/dm/tests/import_goroutine_leak/run.sh#L28-L35
