### ISSUE TITLE
endless loop in mysql sink

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#573]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you see instead?

full cdc log: http://fileserver.pingcap.net/download/logs/pingcap/cdc/2020-05-14.cdc.log.tar.gz

- From cdc log we can see a lot of errors like follows. But processor doesn't exit or meet an error

`[2020/05/14 17:49:42.778 +08:00] [ERROR] [mysql.go:528] ["execute DMLs failed"] [err="context canceled"] [ts="[416662081008304314,...`

- From go routine we can see cdc blocks in 

```
goroutine 688 [chan send]:
github.com/pingcap/ticdc/cdc/sink.concurrentExec.func1(0xc142811bc0, 0xc1428da770, 0x1, 0x1, 0x1)
        github.com/pingcap/ticdc@/cdc/sink/mysql.go:353 +0xb3
github.com/pingcap/ticdc/cdc/sink.concurrentExec(0x248a380, 0xc00463d780, 0xc0d5de70e0, 0x10, 0x100, 0xc0e0dfc820, 0x0, 0xffffffffffffffff)
        github.com/pingcap/ticdc@/cdc/sink/mysql.go:363 +0x55f
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).concurrentExec(0xc0045d9320, 0x248a380, 0xc00463d780, 0xc0d5de70e0, 0x0, 0x0)
        github.com/pingcap/ticdc@/cdc/sink/mysql.go:320 +0x8b
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).FlushRowChangedEvents(0xc0045d9320, 0x248a380, 0xc00463d780, 0x5c8480c25700042, 0x1, 0x0)
        github.com/pingcap/ticdc@/cdc/sink/mysql.go:100 +0x107
github.com/pingcap/ticdc/cdc.(*processor).sinkDriver(0xc0001ec1a0, 0x248a380, 0xc00463d780, 0x0, 0x0)
        github.com/pingcap/ticdc@/cdc/processor.go:611 +0x13b
github.com/pingcap/ticdc/cdc.(*processor).Run.func3(0xc000c22f68, 0x0)
        github.com/pingcap/ticdc@/cdc/processor.go:213 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0048a4690, 0xc00488e7c0)
        golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

4. Versions of the cluster

    - TiCDC version (execute `cdc version`):

        ```
        [2020/05/14 14:29:39.581 +08:00] [INFO] [version.go:34] ["Welcome to Change Data Capture (CDC)"] [release-version=v4.0.0-rc.2-5-g29828b5] [git-hash=29828b5bbfde1b5e3d8d6c3ec4c926b47e7bc7a0] [git-branch=master] [utc-build-time="2020-05-14 05:33:15"] [go-version="go version go1.13.6 linux/amd64"]
        ```

**Comment by aytrack** [comment]
Test Process：
1.  Add `shuffle-leader-scheduler, shuffle-region-scheduler` and remove other schedulers.
2. create `chagefeed` and run `bank` test on the upstream cluster.
3. set config as follows
```
set config tikv coprocessor.`region-split-keys`='10000';
set config tikv coprocessor.`region-max-keys`='10000';
set config tikv coprocessor.`region-split-size`='10M';
set config tikv coprocessor.`region-max-size`='10M';
```
got some errors 
```
[2020/05/14 15:08:12.627 +08:00] [ERROR] [client.go:649] ["send request to stream failed"] [addr=172.16.4.184:20160] [storeID=7] [regionID=8] [requestID=9446] [error=EOF]
t: connection refused\""]
...
[2020/05/14 15:13:56.391 +08:00] [INFO] [client.go:302] ["establish stream to store failed, retry later"] [addr=172.16.4.184:20160] [error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.16.4.184:20160: connect: connection refused\""]
[2020/05/14 15:13:56.394 +08:00] [INFO] [client.go:302] ["establish stream to store failed, retry later"] [addr=172.16.4.184:20160] [error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.16.4.184:20160: connect: connection refused\""]
[2020/05/14 15:13:56.401 +08:00] [ERROR] [processor.go:850] ["error on running processor"] [captureid=6f458915-8af4-46a1-aac7-461193ca6a04] [changefeedid=3cb15775-ab53-4151-8d07-a8aa7c7478ca] [processorid=d22930be-426a-4a1b-8288-64cf9d1e47fb] [error="can not found schema snapshot, the specified ts(416662182995427524) is more than resolvedTs(416662182995427417): unresolved"] [errorVerbose="unresolved\ncan not found schema snapshot, the specified ts(416662182995427524) is more than resolvedTs(416662182995427417)\ngithub.com/pingcap/ticdc/cdc/entry.(*SchemaStorage).getSnapshot\n\tgithub.com/pingcap/ticdc@/cdc/entry/schema_storage.go:668\ngithub.com/pingcap/ticdc/cdc/entry.(*SchemaStorage).GetSnapshot.func1\n\tgithub.com/pingcap/ticdc@/cdc/entry/schema_storage.go:692\ngithub.com/pingcap/ticdc/pkg/retry.Run.func1\n\tgithub.com/pingcap/ticdc@/pkg/retry/retry.go:31\ngithub.com/cenkalti/backoff.RetryNotify\n\tgithub.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:37\ngithub.com/cenkalti/backoff.Retry\n\tgithub.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:24\ngithub.com/pingcap/ticdc/pkg/retry.Run\n\tgithub.com/pingcap/ticdc@/pkg/retry/retry.go:30\ngithub.com/pingcap/ticdc/cdc/entry.(*SchemaStorage).GetSnapshot\n\tgithub.com/pingcap/ticdc@/cdc/entry/schema_storage.go:684\ngithub.com/pingcap/ticdc/cdc/entry.(*mounterImpl).unmarshalAndMountRowChanged\n\tgithub.com/pingcap/ticdc@/cdc/entry/mounter.go:215\ngithub.com/pingcap/ticdc/cdc/entry.(*mounterImpl).codecWorker\n\tgithub.com/pingcap/ticdc@/cdc/entry/mounter.go:166\ngithub.com/pingcap/ticdc/cdc/entry.(*mounterImpl).Run.func2\n\tgithub.com/pingcap/ticdc@/cdc/entry/mounter.go:143\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57\nruntime.goexit\n\truntime/asm_amd64.s:1357"]
[2020/05/14 15:13:56.401 +08:00] [ERROR] [client.go:925] ["failed to receive from stream"] [addr=172.16.4.116:20160] [storeID=1] [error="rpc error: code = Canceled desc = context canceled"]
[2020/05/14 15:13:56.401 +08:00] [ERROR] [client.go:925] ["failed to receive from stream"] [addr=172.16.4.116:20160] [storeID=1] [error="rpc error: code = Canceled desc = context canceled"]
[2020/05/14 15:13:56.401 +08:00] [INFO] [client.go:895] ["stream to store closed"] [addr=172.16.4.116:20160] [storeID=1]
[2020/05/14 15:13:56.401 +08:00] [INFO] [client.go:895] ["stream to store closed"] 
[addr=172.16.4.116:20160] [storeID=1]
[2020/05/14 15:13:56.530 +08:00] [ERROR] [client.go:649] ["send request to stream failed"] [addr=172.16.4.116:20160] [storeID=1] [regionID=1137] [requestID=38812] [error=EOF]

```
4. reset the config as default.
