### ISSUE TITLE
panic: TableSchemaStore is not initialized

### ISSUE THREAD

**Issue by wlwilliamx** [pingcap/ticdc#668]
```log
panic: TableSchemaStore is not initialized [recovered]
        panic: handleLoop panic

goroutine 914 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc00ac249c0, {0x48?, 0xc00ac2db00?, 0x895?})
        /root/.gvm/pkgsets/go1.21.7/global/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:196 +0x9f
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00ac249c0, {0xc00a0fca00, 0x2, 0x2})
        /root/.gvm/pkgsets/go1.21.7/global/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:262 +0x3ad
go.uber.org/zap.(*Logger).Panic(0xc0035ca100, {0xbeee2c7, 0x10}, {0xc00a0fca00, 0x2, 0x2})
        /root/.gvm/pkgsets/go1.21.7/global/pkg/mod/go.uber.org/zap@v1.27.0/logger.go:285 +0x68
github.com/pingcap/log.Panic({0xbeee2c7, 0x10}, {0xc00a0fca00, 0x2, 0x2})
        /root/.gvm/pkgsets/go1.21.7/global/pkg/mod/github.com/pingcap/log@v1.1.1-0.20240314023424-862ccc32f18d/global.go:54 +0x72
github.com/pingcap/ticdc/utils/dynstream.(*stream[...]).handleLoop.func2()
        /root/workspace/repo/ticdc/utils/dynstream/stream.go:346 +0x2cb
panic({0xb0fc560?, 0xc0019edc90?})
        /root/.gvm/pkgsets/go1.21.7/global/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.linux-amd64/src/runtime/panic.go:785 +0x132
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc00ac248f0, {0x46?, 0xc000135180?, 0x577?})
        /root/.gvm/pkgsets/go1.21.7/global/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:196 +0x9f
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00ac248f0, {0xc00a0ef300, 0x1, 0x1})
        /root/.gvm/pkgsets/go1.21.7/global/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:262 +0x3ad
go.uber.org/zap.(*Logger).Panic(0xc0035ca100, {0xbf866cc, 0x23}, {0xc00a0ef300, 0x1, 0x1})
        /root/.gvm/pkgsets/go1.21.7/global/pkg/mod/go.uber.org/zap@v1.27.0/logger.go:285 +0x68
github.com/pingcap/log.Panic({0xbf866cc, 0x23}, {0xc00a0ef300, 0x1, 0x1})
        /root/.gvm/pkgsets/go1.21.7/global/pkg/mod/github.com/pingcap/log@v1.1.1-0.20240314023424-862ccc32f18d/global.go:54 +0x72
github.com/pingcap/ticdc/pkg/sink/util.(*TableSchemaStore).initialized(0x0)
        /root/workspace/repo/ticdc/pkg/sink/util/helper.go:117 +0x1fe
github.com/pingcap/ticdc/pkg/sink/util.(*TableSchemaStore).GetTableIdsByDB(0x0, 0x80)
        /root/workspace/repo/ticdc/pkg/sink/util/helper.go:124 +0x85
github.com/pingcap/ticdc/pkg/sink/mysql.(*MysqlWriter).SendDDLTs(0xc0015363c0, 0xc00a389e00)
        /root/workspace/repo/ticdc/pkg/sink/mysql/mysql_writer.go:262 +0x546
github.com/pingcap/ticdc/pkg/sink/mysql.(*MysqlWriter).FlushDDLTs(0xc0015363c0, 0xc00a389e00)
        /root/workspace/repo/ticdc/pkg/sink/mysql/mysql_writer.go:131 +0x105
github.com/pingcap/ticdc/pkg/sink/mysql.(*MysqlWriter).FlushDDLEvent(0xc0015363c0, 0xc00a389e00)
        /root/workspace/repo/ticdc/pkg/sink/mysql/mysql_writer.go:110 +0x234
github.com/pingcap/ticdc/downstreamadapter/worker.(*MysqlDDLWorker).WriteBlockEvent(0xc00420a2d0, {0xd052b70, 0xc00a389e00})
        /root/workspace/repo/ticdc/downstreamadapter/worker/mysql_worker.go:187 +0x625
github.com/pingcap/ticdc/downstreamadapter/sink.(*MysqlSink).WriteBlockEvent(0xc004877e80, {0xd052b70, 0xc00a389e00}, 0xc001720af0)
        /root/workspace/repo/ticdc/downstreamadapter/sink/mysql_sink.go:165 +0xe5
github.com/pingcap/ticdc/downstreamadapter/dispatcher.(*Dispatcher).HandleDispatcherStatus(0xc003d48c30, 0xc00aada600)
        /root/workspace/repo/ticdc/downstreamadapter/dispatcher/dispatcher.go:226 +0x3f3
github.com/pingcap/ticdc/downstreamadapter/dispatcher.(*DispatcherStatusHandler).Handle(0xc0015de678?, 0xc003d48c30, {0xc0035786c0, 0x1, 0x1?})
        /root/workspace/repo/ticdc/downstreamadapter/dispatcher/helper.go:297 +0x165
github.com/pingcap/ticdc/utils/dynstream.(*stream[...]).handleLoop(0xd08a300, {0x0, 0x0, 0x0}, {0x0?, 0x0, 0x0})
        /root/workspace/repo/ticdc/utils/dynstream/stream.go:423 +0x991
created by github.com/pingcap/ticdc/utils/dynstream.(*stream[...]).start in goroutine 735
        /root/workspace/repo/ticdc/utils/dynstream/stream.go:268 +0x4fe
```

**Comment by wlwilliamx** [comment]
Code has changed.
